//{{NO_DEPENDENCIES}}
// Microsoft eMbedded Visual C++ generated include file.
// Used by prssr.rc
//
#define IDI_NOTIFY                      203

#define IDD_ABOUTBOX                    100
#define IDD_ABOUTBOX_WIDE               101
#define IDD_ARTICLE                     102
#define IDD_ARTICLE_WIDE                103
#define IDD_DOWNLOAD                    104
#define IDD_IMPORT_OPML                 106
#define IDD_IMPORT_OPML_WIDE            107
#define IDD_OPT_APPEARANCE              108
#define IDD_OPT_GENERAL                 110
#define IDD_OPT_STORAGE                 112
#define IDD_OPT_READ                    114
#define IDD_OPT_RETRIEVAL               116
#define IDD_OPT_HTML                    118
#define IDD_OPT_CACHING                 120
#define IDD_OPT_MAINTENANCE             122
#define IDD_OPT_CACHE                   124
#define IDD_OPT_ADVANCED                126
#define IDD_OPT_ENCLOSURES              128
#define IDD_OPT_CONNECTION              130
#define IDD_INFO_CHANNEL                132
#define IDD_INFO_DESCRIPTION            134
#define IDD_INFO_GENERAL                136
#define IDD_PROP_OPTIONS                138
#define IDD_PROP_CACHING                140
#define IDD_PROP_AUTHENTICATION         142
#define IDD_PROP_KEYWORDS               144
#define IDD_EDIT_CACHING                146
#define IDD_SITE_MANAGER                148
#define IDD_SITE_MANAGER_WIDE           149
#define IDD_ADD_FEED                    150
#define IDD_ADD_FEED_WIDE               151
#define IDD_COLOR                       152
#define IDD_BROWSE                      154
#define IDD_BROWSE_WIDE                 155
#define IDD_EDIT_SITE                   156
#define IDD_ERRORS                      158
#define IDD_ERRORS_WIDE                 159
#define IDD_ADD_OFFLINE                 162
#define IDD_ADD_OFFLINE_WIDE            163
#define IDD_SEARCH                      164
#define IDD_SEARCH_WIDE                 165
#define IDD_PROGRESS                    166
#define IDD_PROGRESS_WIDE               167
#define IDD_KEYWORD_MANAGER             168
#define IDD_KEYWORD_MANAGER_WIDE        169
#define IDD_CACHE_MANAGER               170
#define IDD_CACHE_MANAGER_WIDE          171
#define IDD_UPDATE_FINISHED             174
#define IDD_REWRITE_RULE                176
#define IDD_ACCEPT_CERTIFICATE          178
#define IDD_IMPORT_FEEDS                180
#define IDD_IMPORT_FEEDS_WIDE           181
#define IDD_CLEAR_CACHE                 182
#define IDD_AUTHENTICATION              184
#define IDD_OPT_HW_KEYS                 186
#define IDD_GRAB_KEY                    188
#define IDD_SEARCH_RESULTS              190
#define IDD_SEARCH_RESULTS_WIDE         191
#define IDD_UPDATE_SITES                192
#define IDD_UPDATE_SITES_WIDE           193
#define IDD_PROP_GENERAL                194
#define IDD_PROP_ARCHIVE                196
#define IDD_PROP_UPDATING               198
#define IDD_PROXY                       200
#define IDD_CHOOSE_FEEDS                202
#define IDD_CHOOSE_FEEDS_WIDE           203
#define IDD_REWRITING                   204
#define IDD_LICENSE                     205
#define IDD_LICENSE_WIDE                206
#define IDD_CREDITS                     207
#define IDD_CREDITS_WIDE                208
#define IDD_OPT_SYNC                    209

#define IDR_FEEDITEM                    300
#define IDR_EDIT                        301
#define IDR_CACHE                       302
#define IDR_OPEN                        303
#define IDR_ERRORS                      304
#define IDR_SUMMARYVIEW                 305
#define IDR_CANCEL                      306
#define IDR_OPEN_ONLINE                 307
#define IDR_ADD_SITE                    308
#define IDR_SITE_MAN_CTX_MNU_EDIT       309
#define IDR_SITE_MAN_CTX_MNU_ADD        310
#define IDR_SITE_MAN_CTX_MNU_MOVE_TO    311
#define IDR_SUMMARY_VIEW_CONTEXT_MENU   312
#define IDR_COPY_URL                    313
#define IDR_COPY                        314
#define IDR_SITEMAN_ADD                 315
#define IDR_SITE_MANAGER_GROUP_CONTEXT_MENU 316
#define IDR_IMPORT_FEEDS                317
#define IDR_BROWSE                      318
#define IDR_REFRESH                     319
#define IDR_SITE_MANAGER                320
#define IDR_EXPORT_OPML                 321
#define IDR_SEARCH                      322
#define IDR_ADD                         323
#define IDR_IMPORT_OPML                 324
#define IDR_ARTICLE                     325
#define IDR_UPDATE_SITES                326
#define IDR_ENCLOSURES                  327
#define IDR_ITEM_FLAG                   328
#define IDR_ITEM_OPER                   329
#define IDR_KEYWORD_MANAGER_CTX         330
#define IDR_OPTIONS                     331
#define IDR_LINK_CTX                    332
#define IDR_SORT                        333
#define IDR_SEND_BY_EMAIL               334
#define IDR_YESNO                       335
#define IDR_CACHE_MANAGER               336
#define IDR_ARTICLE_IMAGE               337
#define IDR_COPY_LINK_URL               338
#define IDR_REWRITE_CTX                 339
#define IDR_DONE                        340
#define IDR_KEYWORD_MANAGER             341
#define IDR_FULLSCREEN                  342
#define IDR_REWRITING                   343

#define IDS_TODAY                       400
#define IDS_YESTERDAY                   401
#define IDS_PROPERTIES                  402
#define IDS_TOTAL_ITEMS                 403
#define IDS_UNREAD_ITEMS                404
#define IDS_NEW_ITEMS                   405
//#define IDS_SITE                        406
//#define IDS_STATUS                      407
//#define IDS_WAITING                     408
#define IDS_DOWNLOADING                 409
#define IDS_DONE                        410
#define IDS_ERROR                       411
#define IDS_UNKNOWN                     412
#define IDS_CLOSE                       413
#define IDS_CONNECTING                  414
#define IDS_SENDING_REQUEST             415
#define IDS_DOWNLOAD_ERROR              416
#define IDS_ERROR_SENDING_REQUEST       417
#define IDS_CANT_CONNECT                418
#define IDS_OK                          419
#define IDS_OPTIONS                     420
#define IDS_FEED_FMT                    421
#define IDS_INVALID_FILE_FORMAT         422
#define IDS_DELETE_ITEMS                423
#define IDS_ERROR_LOADING_OPML          425
#define IDS_SELECT_CACHE_LOCATION       426
#define IDS_LOCATION_NOT_DIR            427
#define IDS_ERROR_MOVING_CACHE          428
#define IDS_CANCEL                      429
#define IDS_DIRECTORY_NOT_CREATED       430
#define IDS_CLEARCACHE                  431
//#define IDS_CLEAR_ENCLOSURES            431
#define IDS_SITENAME_IS_EMPTY           432
//#define IDS_CACHING                     433
//#define IDS_CACHING_IMAGES              434
//#define IDS_EXECUTING                   435
//#define IDS_FINISHED                    436
//#define IDS_CACHING_ONLINE_CONTENT      437
//#define IDS_SELECT_EXTERNAL_BROWSER     438
#define IDS_LOADING                     439
#define IDS_NOT_FILE                    440
#define IDS_ERRORS                      441
#define IDS_CANT_CONNECT_TO_INTERNET    442
#define IDS_CONNECTING_TO_INTERNET      443
#define IDS_DAYS_AGO                    444
#define IDS_MOVE_TO_FEED                445
#define IDS_TIME                        446
#define IDS_ROOT_GROUP                  448
#define IDS_TRANSLATING_FOR_OFFLINE     450
#define IDS_HOURLY                      451
#define IDS_DAILY                       452
#define IDS_NEVER                       453
#define IDS_SELECT_ENCLOSURES_LOCATION  454
#define IDS_CACHING_ENCLOSURES          455
#define IDS_OVERWRITE_OPML              456
#define IDS_CACHING_REMAIN              457
#define IDS_SELECT_EXPORT_LOCATION      458
#define IDS_CANT_EXPORT_FILE            459
#define IDS_EXPORT_OK                   460
#define IDS_SELECT_FILE_TO_IMPORT       461
#define IDS_CANT_IMPORT_FILE            462
#define IDS_INVALID_URL                 463
#define IDS_WARNING                     464
#define IDS_NO_INTERNET_CONNECTION      465
#define IDS_UPDATING                    466
#define IDS_NONE                        467
#define IDS_ERROR_PARSING_OPML          468
#define IDS_UNKNOWN_ERROR               469
#define IDS_EMPTY_HOSTNAME              470
#define IDS_BAD_PORTNUM                 471
#define IDS_AUTHORIZATION_REQUIRED      473
#define IDS_ERROR_GETTING_RESPONSE      474
#define IDS_BAD_AUTHENTICATION_RESPONSE 475
#define IDS_RESPONSE_ERROR              476
#define IDS_CANT_CONNECT_TO             477
#define IDS_NO_LOCATION_HEADER          478
#define IDS_HTTP_ERROR                  479
#define IDS_MALFORMED_URL               480
#define IDS_ERROR_PARSING_FEED_FILE     481
#define IDS_INVALID_FEED_FILE           482
#define IDS_SOME_FILES_WERE_NOT_CACHED  483
#define IDS_ENCLOSURE                   484
#define IDS_UNREAD                      485
#define IDS_TOTAL                       486
#define IDS_FAILED                      487
#define IDS_MYDEVICE                    488
#define IDS_UNKNOWN_AUTH_SCHEME         489
#define IDS_PROXY_NEEDS_AUTH            490
#define IDS_KEYWORD                     491
#define IDS_CACHE_MANAGER               492
#define IDS_CACHE                       493
#define IDS_ENCLOSURES                  494
#define IDS_NO_ITEMS_TO_DISPLAY         495
#define IDS_NO_ERRORS_TO_DISPLAY        496
#define IDS_NO_KEYWORDS_DEFINED         497
#define IDS_RETURN_TO_MAINLIST          498
#define IDS_OPEN_ONLINE_MESSAGE         499
#define IDS_MIN15                       500
#define IDS_MIN30                       501
#define IDS_HOUR1                       502
#define IDS_HOUR2                       503
#define IDS_HOUR3                       504
#define IDS_HOUR4                       505
#define IDS_HOUR8                       506
#define IDS_HOUR24                      507
#define IDS_TEXT                        508
#define IDS_FRAME                       509
#define IDS_BACKGROUND                  510
#define IDS_MESSAGE_BACKGROUND          511
#define IDS_TITLE_BACKGROUND            512
#define IDS_TITLE_FOREGROUND            513
#define IDS_MAIN_WINDOW                 515
#define IDS_KEYWORD_MANAGER             517
#define IDS_ADD_SITE                    519
#define IDS_AUTHENTICATION              520
#define IDS_SELECT_COLOR                521
#define IDS_FEED_NOT_FOUND              522
#define IDS_ERROR_GETTING_FILE          523
#define IDS_PLAYLIST_WAS_NOT_GENERATED  524
#define IDS_ERROR_SAVING_OPML           525
#define IDS_NAME_CAN_NOT_BE_EMPTY       526
#define IDS_URL_CAN_NOT_BE_EMPTY        527
#define IDS_SITE_RENAME                 528
#define IDS_DESCRIPTION                 529
#define IDS_SEARCHING                   530
#define IDS_FOUND_SITES                 531
#define IDS_XML_RPC_RESPONSE_ERROR      532
#define IDS_UPDATE_FINISHED_ERROR       533
#define IDS_URL_REWRITING               534
#define IDS_CACHED                      535
#define IDS_KEYWORDS                    536
#define IDS_UNSAFE_LOCATION             537
#define IDS_MOVE_CONTENT                538
#define IDS_READING_DIR_STRUCTURE       539
#define IDS_MOVING                      540
#define IDS_CLEANING_UP                 541
#define IDS_ERROR_DOWNLOADING_FILE      542
#define IDS_BANNER_BACKGROUND           543
#define IDS_BANNER_FOREGROUND           545
#define IDS_MINUTES_AGO                 547
#define IDS_HOURS_AGO                   548
#define IDS_SUGGEST_INTERVAL            549
#define IDS_NO_SUGGEST_INTERVAL         550
#define IDS_ANALYZING_CACHE             551
#define IDS_PURGING_CACHE               552
#define IDS_REMOVING_FILES              553
#define IDS_NO_FEEDS_DEFINED            554
#define IDS_BUTTON                      556
#define IDS_ACTION                      557
#define IDS_OPEN_ENCLOSURE              558
#define IDS_OPEN_SITE_LIST              559
#define IDS_UPDATE_CHANNEL              561
#define IDS_UPDATE_ALL_CHANNELS         562
#define IDS_MY_CHANNELS					563
#define IDS_MOVE_TO                     564
#define IDS_HERE                        565
#define IDS_GO_ONLINE                   566
#define IDS_CACHE_NOT_AVAILABLE         567
//
#define IDS_SITE_MANAGER                424
#define IDS_EXPORT_OPML_FILE            569
//#define IDS_SEARCH                      570
//#define IDS_CONNECTING                  571
#define IDS_CONNECTED                   572
//#define IDS_SENDING_REQUEST             573
#define IDS_GETTING_RESPONSE            574
#define IDS_DATA_TRANSFER               575
#define IDS_ERROR_CONNECT               576
#define IDS_AUTHORIZATION_FAILED        577
#define IDS_AUTHENTICATION_ERROR        578

#define IDS_ERROR_XML_RPC_RESPONSE      580
#define IDS_NO_SEARCH_RESULTS           581
//#define IDS_SEARCH_RESULTS              582
#define IDS_IMPORT_OPML_FILE            518
//#define IDS_IMPORT_FEEDS                546
//#define IDS_NEW_SUBSCRIPTION            583
#define IDS_N_ERRORS                    584

//#define IDS_UPDATE_SITES                585
#define IDS_EMPTY                       586
//#define IDS_FEED_INFORMATION            587
#define IDS_DELETE_KEYWORDS             588
#define IDS_PROFILE                     589
#define IDS_DELETE_PROXY_PROFILE        590
#define IDS_DOWNLOADING_FEED            591

#define IDS_BOOKMARK_AT                 592
#define IDS_BAD_URL_FMT_SBS             593

// color
#define IDS_ARTICLE_FG                  594
#define IDS_ARTICLE_BG                  595
#define IDS_SUMMARY_FG                  596
#define IDS_SUMMARY_BG                  597
#define IDS_GROUP_FG                    598
#define IDS_GROUP_BG                    599
#define IDS_FEEDVIEW_BG                 600
#define IDS_FEEDVIEW_FG                 601
#define IDS_VFOLDER_FG                  602
#define IDS_VFOLDER_BG                  603
#define IDS_DATE                        604
// fonts
#define IDS_MESSAGE_READING             620
#define IDS_FEED_VIEW                   621
#define IDS_SUMMARY_VIEW                622

#define IDS_NO_MORE_MESSAGES            630
#define IDS_FEED_NOT_ADDED              631
//#define IDS_CHOOSE_FEEDS                632
#define IDS_FLAGGED                     633
#define IDS_DELETING                    634
#define IDS_NEW_RULE                    635
#define IDS_NEW_KEYWORD                 636
#define IDS_DELETE_RULE                 637
#define IDS_OPEN                        638
#define IDS_HIDE                        639
#define IDS_PRSSR_NOTIFICATION          640
#define IDS_LINK_TO_ARTICLE             641
#define IDS_NOTHING_TO_DISPLAY          642
#define IDS_SCANNING_FOR_KEYWORDS       643
#define IDS_NO_FEEDS_SUMM               644
#define IDS_OPEN_SITE_MAN               645
#define IDS_EMPTY_RULE                  646
#define IDS_EMPTY_NAME                  647
#define IDS_EMPTY_HOST_NAME             648
#define IDS_ABOUT                       649
#define IDS_PURGE_CACHE_WARNING	        650
#define IDS_AUTHENTICATING              651
#define IDS_AUTHENTICATION_FAILED       652
#define IDS_SYNCING                     653
#define IDS_ERROR_GETTING_TOKEN         654
#define IDS_DISK_FULL                   655

// controls
#define IDC_HTML                        1000
#define IDC_SECONDS                     1001
#define IDC_LEVEL                       1002
#define IDC_IMPORT_NOW                  1003
#define IDC_SVALUE                      1004
#define IDC_STATUS                      1005
#define IDC_LVALUE                      1006
#define IDC_GVALUE                      1008
#define IDC_ERROR                       1009
#define IDC_BVALUE                      1010
#define IDC_CLOSE                       1011
#define IDC_URL                         1012
#define IDC_ADD                         1013
#define IDC_SITES                       1014
#define IDC_REMOVE                      1015
#define IDC_DOWNLOAD_PROGRESS           1016
#define IDC_IMPORT                      1017
#define IDC_FORMAT                      1018
#define IDC_EXPORT                      1018
#define IDC_EDIT                        1019
#define IDC_WWW                         1020
#define IDC_RSS                         1021
#define IDC_UPDATES                     1022
#define IDC_SITENAME                    1023
#define IDC_FILESIZE                    1024
#define IDC_TOTALITEMS                  1025
#define IDC_UNREADITEMS                 1026
#define IDC_NEWITEMS                    1027
#define IDC_LASTUPDATED                 1028
#define IDC_PUBLISHED                   1029
#define IDC_LASTSTATUS                  1030
#define IDC_LANGUAGE                    1031
#define IDC_COPYRIGHT                   1032
#define IDC_UPDATE_INTERVAL             1033
#define IDC_PLAYLIST_FORMAT             1034
#define IDC_TYPE                        1035
#define IDC_CACHE_SIZE                  1036
#define IDC_CLEAR_CACHE                 1037
#define IDC_BROWSE                      1038
#define IDC_CLEAR_ERRORLOG              1039
#define IDC_BROWSE_ENCLOSURES           1040
#define IDC_CLEARTYPE                   1041
#define IDC_ITEM_COLOR                  1042
#define IDC_MOVE_UP                     1043
#define IDC_NEW_FOLDER                  1044
#define IDC_MOVE_DOWN                   1045
#define IDC_DESCRIPTION                 1046
#define IDC_FOLDER                      1047
#define IDC_LOCATION                    1048
#define IDC_HRULE                       1049
#define IDC_ENCLOSURES_LOCATION         1050
#define IDC_ERROR_LBL                   1051
#define IDC_HRULE2                      1052
#define IDC_LOCATION_LBL                1053
#define IDC_CACHE_LBL                   1054
#define IDC_CACHINGOPT_LBL              1055
#define IDC_GENERAL_LBL                 1056
#define IDC_FONT_SIZE                   1057
#define IDC_PLAYLIST_LBL                1058
#define IDC_ITEMOPT_LBL                 1059
#define IDC_OPTIONS_LBL                 1060
#define IDC_FONT_LBL                    1061
#define IDC_FONT_NAME                   1062
#define IDC_COLORS_LBL                  1063
#define IDC_ITEM                        1064
#define IDC_CLEARTYPE_LBL               1065
#define IDC_COLOR_LBL                   1066
#define IDC_HSPIN                       1067
#define IDC_SSPIN                       1068
#define IDC_LSPIN                       1069
#define IDC_HVALUE                      1070
#define IDC_LIGHTNESS                   1071
#define IDC_HSFIELD                     1072
#define IDC_RVALUE                      1073
#define IDC_RSPIN                       1074
#define IDC_GSPIN                       1075
#define IDC_BSPIN                       1076
#define IDC_COLOR                       1077
#define IDC_STATUS_LBL                  1078
#define IDC_VERIFY_LBL                  1079
#define IDC_BANNER                      1080
#define IDC_CAPTION                     1081
#define IDC_DIRS                        1082
#define IDC_PATH                        1083
#define IDC_IMPORT_LBL                  1084
#define IDC_ACTION_BUTTON               1085
#define IDC_SHOW_BANNER                 1086
#define IDC_READ_LBL                    1087
#define IDC_BUTTONS_LBL                 1088
#define IDC_SCHEDULE_INTERVAL           1089
#define IDC_EXTERNAL                    1090
#define IDC_CRADLED                     1091
#define IDC_ACTIONBUTTON_LBL            1092
#define IDC_AUTO_CONNECT                1093
#define IDC_CACHE_ONLINE_CONTENT        1094
#define IDC_LEVEL_SPIN                  1095
#define IDC_EXTERNAL_BROWSER            1096
#define IDC_UPDATE_SETTINGS_LBL         1097
#define IDC_EVENTS_LBL                  1098
#define IDC_OFFLINE_LBL                 1099
#define IDC_USERAGENT_LBL               1100
#define IDC_MAX_LBL                     1101
#define IDC_LEVEL_LBL                   1102
#define IDC_STORE_IMAGES                1103
#define IDC_CLEAR_CACHE_BEFORE_UPDATE   1104
#define IDC_TODAY_SCREEN_LBL2           1105
#define IDC_TODAY_SCREEN_LBL            1106
#define IDC_ENCLOSURES_LBL              1107
#define IDC_CLEARCACHEBEFOREUPDATE      1108
#define IDC_OFFLINE_ADD                 1109
#define IDC_SITENAME_LBL                1110
#define IDC_USE_ON_MWND                 1111
#define IDC_UPDATE_LBL                  1112
#define IDC_PROGRESS                    1113
#define IDC_ITEMOPTIONS_LBL             1114
#define IDC_NOTIFY_NEW                  1115
#define IDC_TRUNCITEMTITLES             1116
#define IDC_ERRORS                      1117
#define IDC_CHANNELOPTIONS_LBL          1118
#define IDC_SHOW_ON_TODAY               1119
#define IDC_READOPTIONS_LBL             1120
#define IDC_MOVETOUNREAD                1121
#define IDC_SECONDS_SPIN                1122
#define IDC_CHANNELMOVE                 1123
#define IDC_UPDATEOPTIONS_LBL           1124
#define IDC_RESET                       1125
#define IDC_HTTP_AUTH_LBL               1126
#define IDC_USERNAME                    1127
#define IDC_PASSWORD                    1128
#define IDC_KEYWORDS                    1129
#define IDC_NEW                         1130
#define IDC_OVERRIDE_UPDATE             1131
#define IDC_CACHE_ENCLOSURES            1132
#define IDC_DONT_CACHE                  1133
#define IDC_MB                          1135
#define IDC_ENCLOSURE_LIMIT             1136
#define IDC_MB_LBL                      1137
#define IDC_UPDATEEVERY_LBL             1138
#define IDC_UPDATE_PROGRESS             1139
#define IDC_UPDATE_STOP                 1140
#define IDC_GENERATE_PLAYLISTS          1141
#define IDC_GMT                         1142
#define IDC_HRULE1                      1143
#define IDC_HRULE3                      1144
#define IDC_HOMEPAGE_LINK               1145
#define IDC_SITELIST                    1146
#define IDC_GMT_TIMES                   1147
#define IDC_IMAGES                      1148
#define IDC_ENCLOSURES                  1149
#define IDC_HOSTNAME                    1150
#define IDC_PORT                        1151
#define IDC_C_HOST                      1152
#define IDC_C_PORT                      1153
#define IDC_C_USERNAME                  1154
#define IDC_C_PASSWORD                  1155
#define IDC_AUTH_REQUIRED               1156
#define IDC_PROXYSERVER_LBL             1157
#define IDC_AUTH_NEEDED                 1158
#define IDC_CACHEONLYNEW                1159
#define IDC_MARKNEWUNREAD               1160
#define IDC_AUTHENTICATION_LBL          1161
#define IDC_CACHEITEMS                  1162
#define IDC_CACHENOW                    1163
#define IDC_DELETE                      1164
#define IDC_CACHE_LOCATION              1165
#define IDC_BROWSE_CACHE                1166
#define IDC_OVERRIDE_CONMAN             1167
#define IDC_C_TYPE                      1168
#define IDC_USERAGENT                   1169
#define IDC_FONT_ITEM                   1170
#define IDC_APPICON                     1171
#define IDC_TITLE                       1172
#define IDC_SITEURL                     1173
#define IDC_RENAME                      1174
#define IDC_WHAT                        1175
#define IDC_RESULTS                     1176
#define IDC_SEARCH                      1177
#define IDC_URL_REWRITING               1178
#define IDC_REPLACE                     1179
#define IDC_HTML_LBL                    1180
#define IDC_USE_OPTIMIZER               1181
#define IDC_WARN_FEED_MOVE              1184
#define IDC_TEXT                        1185
#define IDC_ALERT_ICON                  1186
#define IDC_FEEDS                       1187
#define IDC_APPEND_FEEDS                1188
#define IDC_DO_NOT_IMPORT_SAME          1189
#define IDC_RELATIVE_TIMES              1190
#define IDC_UPDATE_INTERVAL_SPIN        1191
#define IDC_USE_GLOBAL                  1192
#define IDC_FEED_SPECIFIC               1193
#define IDC_NO_AUTO                     1194
#define IDC_SUGGEST_INTERVAL            1195
#define IDC_MINUTES                     1196
#define IDC_SUBTEXT                     1197
#define IDC_STATIC1                     1198
#define IDC_STATIC2                     1199
#define IDC_STATIC3                     1200
#define IDC_STATIC4                     1201
#define IDC_STATIC5                     1202
#define IDC_STATIC6                     1203
#define IDC_STATIC7                     1204
#define IDC_STATIC8                     1205
#define IDC_STATIC9                     1206
#define IDC_SET                         1207
#define IDC_CLEAR                       1208
#define IDC_BUTTONS                     1209
#define IDC_SITE                        1210
#define IDC_REALM                       1211
#define IDC_SAVE_PASSWORD               1212
#define IDC_NAME                        1213
#define IDC_CHECK_FEED_ONLINE           1214
#define IDC_UPDATE_TEXT                 1215
#define IDC_SELECT_ALL                  1216
#define IDC_DEFAULT_SETTINGS            1217
#define IDC_DISABLE_CACHE               1218
#define IDC_UNLIMITED_CACHE             1219
#define IDC_LIMIT_CACHE                 1220
#define IDC_CACHE_ITEMS                 1221
#define IDC_CACHE_ITEMS_SPIN            1222
#define IDC_ITEMS                       1223
#define IDC_FEED_ITEMS                  1224
#define IDC_FEED_ITEMS_SPIN             1225
#define IDC_ENCLOSUREBAR                1226
#define IDC_SPECIFIC_CACHING            1227
#define IDC_PROXIES                     1228
#define IDC_MANAGE                      1229
#define IDC_PROFILES                    1230
#define IDC_SETTINGS                    1231
#define IDC_HOST                        1232
#define IDC_USE_AUTHENTICATION          1233
#define IDC_TIME                        1234
#define IDC_TIME_UPDATE                 1235
#define IDC_OPTIMIZER_LBL               1236
#define IDC_PERIODIC_UPDATE             1237
#define IDC_MISC_LBL                    1238
#define IDC_INFO_BAR                    1239
#define IDC_RULES                       1240
#define IDC_MATCH                       1241
#define IDC_UPDATE_ONLY                 1242
#define IDC_LASTUPDATED_LBL             1243
#define IDC_SITEMAN_LINK                1244
#define IDC_BKGND_UPDATE                1245
#define IDC_LICENSE                     1246
#define IDC_CREDITS                     1247
#define IDC_SYNC_SITE                   1248
#define IDC_SYNC_USERNAME               1249
#define IDC_SYNC_PASSWORD               1250

#define ID_TOOLS_OPTIONS                32774
#define ID_TOOLS_SITEMANAGER            32775
#define ID_TOOLS_IMPORT                 32776
#define ID_TOOLS_MARKITEMUNREAD         32781
#define ID_TOOLS_MARKALLITEMSREAD       32782
#define ID_TOOLS_MARKALLITEMSUNREAD     32796

#define ID_ITEM                         32786
#define ID_ITEM_OPEN                    32787
//#define ID_ITEM_OPEN_ONLINE             32788
#define ID_ITEM_MARKASNEW               32816
#define ID_ITEM_MARKASREAD              32789
#define ID_ITEM_MARKASUNREAD            32790
#define ID_ITEM_FLAG                    32841
#define ID_ITEM_DELETE                  32839

#define ID_VIEW_HIDEREADITEMS           32797
#define ID_VIEW_SORTBY_DATE             32798
#define ID_VIEW_SORTBY_READ             32799
#define ID_VIEW_SORTBY_COMBINATION      32800
#define ID_EDIT                         32801
#define ID_CACHE_GET_ONLINECONTENT      32808
#define ID_CACHE_GET_IMAGES             32850
#define ID_CACHE_DELETEOFFLINECONTENT   32810
#define ID_ENCLOSURE_GET                32809
#define ID_ENCLOSURE_DELETE             32811
#define ID_ENCLOSURE_OPEN               32812
#define ID_TOOLS_ERRORS                 32817
#define ID_CLEANUP                      32818
#define ID_TOOLS_KEYWORDMANAGER         32822
#define ID_TOOLS_CACHEMANAGER           32823
#define ID_FEED                         32824
//#define ID_FEED_UPDATE                  32827
//#define ID_FEED_MARKALLREAD             32828
//#define ID_FEED_MARKALLUNREAD           32829
#define ID_VIEW_HIDEGROUPS              32831
#define ID_NEW_FOLDER                   32833
#define ID_COPY_URL                     32834
#define ID_COPY_FEED_URL                32835
#define ID_SITE_EDIT                    32836
#define ID_REMOVE                       32837
#define ID_RENAME                       32838
//#define ID_SEL_MARKALLREAD              32838
#define ID_ADD                          32840
#define ID_ADD_FEED                     32843
#define ID_ADD_GROUP                    32844
//#define ID_ADD_OFFLINE                  32844
#define ID_SEARCH_FOR_FEEDS             32845
#define ID_VIEW_SHOWFLAGGEDITEMS        32846
//#define ID_GROUP_RENAME                 32847
//#define ID_GROUP_REMOVE                 32848
#define ID_IMPORT                       32849
#define ID_VIEW_SORT_ASCENDING          32851
#define ID_VIEW_SORT_DESCENDING         32852
#define ID_IMPORT_OPML_FILE             32853
#define ID_EXPORT_OPML_FILE             32854
#define ID_OPEN_ENCLOSURE               32855
#define ID_OPEN_SITE_LIST               32856
#define ID_WORK_OFFLINE                 32857
#define ID_REFRESH                      32858
#define ID_VIEW_HIDEREADFEEDS           32859
#define ID_CACHE_FLAGGED                32860
#define ID_EXPORT                       32861
#define ID_SEARCH                       32862
#define ID_UPDATE                       32863
#define ID_SELECT_ALL                   32864
#define ID_FILE_INFORMATION             32865
#define ID_NEW                          32866
#define ID_UPDATE_CHANNEL               32867
#define ID_OPEN_LINK                    32868
#define ID_DOWNLOAD_LINK                32869
#define ID_SEND_BY_EMAIL                32870
#define ID_VIEW_IMAGE                   32871
#define ID_COPY_IMAGE_LOCATION          32872
#define ID_HIDE                         32873
#define ID_OPEN                         32874
#define ID_CACHE_UNREAD                 32875
#define ID_RETRY                        32876
#define ID_CACHE                        32877
#define ID_PURGE_CACHE                  32878
#define ID_FULLSCREEN                   32879
#define ID_REWRITE_RULES                32880

#define ID_SOCIAL_BOOKMARK_BASE			 33000

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        252
#define _APS_NEXT_COMMAND_VALUE         32853
#define _APS_NEXT_CONTROL_VALUE         1167
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
